Shopper/Shopper/Models/EF/Slide.cs
namespace Shopper.Models.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Slide")]
    public partial class Slide
    {
        public int ID { get; set; }

        [StringLength(250)]
        [Required(ErrorMessage="Nhập ảnh Slide")]
        public string Image { get; set; }
        [Required(ErrorMessage = "Chọn thứ tự trình chiếu")]
        public int? DisplayOrder { get; set; }

        [StringLength(250)]
        public string Link { get; set; }

        [StringLength(100)]
        public string Description { get; set; }

        public DateTime? CreateDate { get; set; }

        [StringLength(50)]
        public string CreateBy { get; set; }

        public DateTime? ModifiedDate { get; set; }

        [StringLength(50)]
        public string ModifiedBy { get; set; }

        [Required(ErrorMessage="Chọn trạng thái")]
        public bool? Status { get; set; }
    }
}

Shopper/Shopper/Areas/Admin/Controllers/SlidesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shopper.Models.EF;
using Shopper.Models.DAO;

namespace Shopper.Areas.Admin.Controllers
{
    public class SlidesController : BaseController
    {
        SliderDAO daoSlider = new SliderDAO();

        //
        // GET: /Admin/Slides/
        public ActionResult Index()
        {
            return View(daoSlider.getSlider());
        }

        [HttpGet]
        public ActionResult CreateNew()
        {
            Slide model = new Slide();
            return View(model);
        }
        [HttpPost]
        public ActionResult CreateNew(Slide model)
        {
            if(ModelState.IsValid){
                try
                {
                    var user = Session[Common.Constans.USER_SESSION] as Shopper.Common.LoginSession;
                    model.CreateBy = user.UserName;
                    model.CreateDate = DateTime.Now;
                    model.Status = model.Status ?? false;
                    if (daoSlider.CreateNew(model))
                    {
                        SetAlert("thêm mới thành công", "success");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        SetAlert("có lỗi xảy ra, hảy thử lại", "error");
                        return View(model);
                    }
                }
                catch
                {
                    SetAlert("có lỗi xảy ra, hảy thử lại", "error");
                    return View(model);
                }
            }
            return View(model);
            
        }

        [HttpGet]
        public ActionResult Edit(long id)
        {
            var model = daoSlider.getByID(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Slide model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = Session[Common.Constans.USER_SESSION] as Shopper.Common.LoginSession;
                    model.ModifiedBy = user.UserName;
                    model.ModifiedDate = DateTime.Now;
                    if (daoSlider.Edit(model))
                    {
                        SetAlert("Sửa thông tin thành công", "success");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        SetAlert("có lỗi xảy ra, hãy thử lại", "error");
                        return View(model);
                    }
                }
                catch
                {
                    SetAlert("có lỗi xảy ra, hãy thử lại", "error");
                    return View(model);
                }
            }
            return View(model);

        }


        public ActionResult Delete(long id)
        {
            try
            {
                if (daoSlider.Delete(id))
                {
                    SetAlert("Xóa thông tin thành công!", "success");
                    return RedirectToAction("Index");
                }
                else
                {
                    SetAlert("có lỗi xảy ra, hãy thử lại", "error");
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                SetAlert("có lỗi xảy ra, hãy thử lại", "error");
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public JsonResult changeStatus(long id)
        {
            var res = daoSlider.ChangeStatus(id);
            return Json(new
            {
                status = res
            });
        }
    }
}

Shopper/Shopper/Areas/Admin/Views/Slides/CreateNew.cshtml
@model Shopper.Models.EF.Slide
@using Shopper.Models.EF;

@{
    ViewBag.Title = "thêm mới Slide";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    Thêm Mới Slide
}
@section footerJS{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script>
        $('form:first').validate();
        $('#btnAddImage').on('click', function (e) {
            e.preventDefault();
            var ck = new CKFinder();
            ck.selectActionFunction = function (url) {
                $('#Image').val(url)
            };
            ck.popup();
        })
    </script>
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="/Admin/Slides/Index" class="btn btn-default btn-sm mr-15"><i class="fa fa-backward"></i>&nbsp;Quay lại</a>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("CreateNew", "Slides", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @style = "color:red;" })
                    @Html.HiddenFor(Model => Model.ID)
                    <div class="form-group">
                        <label>Ảnh bài viết</label>
                        @Html.TextBoxFor(Model => Model.Image, new { @class = "required form-control", title = "nhập ảnh" })
                        @Html.ValidationMessageFor(Model => Model.Image, "", new { style = "color:red;" })
                        <a href="#" class="btn btn-link" id="btnAddImage">Thêm Ảnh</a>
                    </div>
                    <div class="form-group">
                        <label>Thứ tự hiển thị</label>
                        @Html.EditorFor(Model => Model.DisplayOrder)
                        @Html.ValidationMessageFor(Model => Model.DisplayOrder, "", new { style = "color:red;" })
                    </div>
                    <div class="form-group">
                        <label>Trạng thái</label>
                        @Html.EditorFor(Model => Model.Status)
                        @Html.ValidationMessageFor(Model => Model.Status, "", new { style = "color:red;" })
                    </div>
                    <div class="form-group">
                        <label>Mô tả chung</label>
                        @Html.TextAreaFor(Model => Model.Description, new { @class = "form-control", title = "nhập tên mô tả chung" })
                    </div>

                    <input type="submit" value="Tạo Mới" class="btn btn-primary btn-lg btn-block" />
                }
            </div>
            <div class="panel-footer">
                <a href="/Admin/Slides/Index" class="btn btn-default btn-sm mr-15"><i class="fa fa-backward"></i>&nbsp;Quay lại</a>
            </div>
        </div>
    </div>
</div>

Shopper/Shopper/Areas/Admin/Views/Slides/Edit.cshtml
@model Shopper.Models.EF.Slide
@using Shopper.Models.EF;

@{
    ViewBag.Title = "thêm mới Slide";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    Thêm Mới Slide
}
@section footerJS{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script>
        $('form:first').validate();
        $('#btnAddImage').on('click', function (e) {
            e.preventDefault();
            var ck = new CKFinder();
            ck.selectActionFunction = function (url) {
                $('#Image').val(url)
            };
            ck.popup();
        })
    </script>
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="/Admin/Slides/Index" class="btn btn-default btn-sm mr-15"><i class="fa fa-backward"></i>&nbsp;Quay lại</a>
            </div>
            <div class="panel-body">
                @using (Html.BeginForm("Edit", "Slides", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @style = "color:red;" })
                    @Html.Hidden("ID", Model.ID)
                    <div class="form-group">
                        <label>Ảnh bài viết</label>
                        @Html.TextBox("Image", Model.Image, new { @class = "required form-control", title = "nhập ảnh" })
                        <a href="#" class="btn btn-link" id="btnAddImage">Thêm Ảnh</a>
                    </div>
                    <div class="form-group">
                        <label>Thứ tự hiển thị</label>
                        @Html.Editor("DisplayOrder", Model.DisplayOrder)
                    </div>
                    <div class="form-group">
                        <label>Trạng thái</label>
                        @Html.CheckBox("Status", Model.Status)
                    </div>
                    <div class="form-group">
                        <label>Mô tả chung</label>
                        @Html.TextArea("Description", Model.Description, new { @class = "form-control", title = "nhập tên mô tả chung" })
                    </div>

                    <input type="submit" value="Sửa đổi" class="btn btn-primary btn-lg btn-block" />
                }
            </div>
            <div class="panel-footer">
                <a href="/Admin/Slides/Index" class="btn btn-default btn-sm mr-15"><i class="fa fa-backward"></i>&nbsp;Quay lại</a>
            </div>
        </div>
    </div>
</div>

Shopper/Shopper/Areas/Admin/Views/Slides/Index.cshtml
@{
    ViewBag.Title = "slider";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model List<Shopper.Models.EF.Slide>

@section header{
    danh sách các Slide
}

@section footerJS{
    <script src="~/Scripts/jquery-ui-1.11.4.min.js"></script>
    <script>
        $('#confirm-delete').on('show.bs.modal', function (e) {
            $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));

            $('.debug-url').html('Delete URL: <strong>' + $(this).find('.btn-ok').attr('href') + '</strong>');
        });
    </script>
}
<div class="row">
    <div class="col-lg-12">
        <a href="/Admin/Slides/CreateNew" id="btnCreate" class="btn btn-primary pull-right"><i class="fa fa-plus"></i>Tạo mới</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <tr>
                <th style="text-align:center;">Thứ tự chiếu</th>
                <th style="text-align:center;">Ảnh</th>
                <th style="text-align:center;">Sửa</th>
                <th style="text-align:center;">Xóa</th>
            </tr>
            <tbody class="rows">
                @{
                    foreach (var item in Model)
                    {
                        <tr id="row_@item.ID">
                            <td style="text-align:center;">@item.DisplayOrder.Value</td>
                            <td style="text-align:center;"><img src="@item.Image" alt="@item.ID" style="width:40px; height:30px;" /></td>

                            <td style="text-align:center;"><a class="editModel" data-id="@item.ID" href="/Admin/Slides/Edit?id=@item.ID"><i class="fa fa-pencil"></i></a></td>
                            <td style="text-align:center;">
                                <a href="#" data-href="/Admin/Slides/Delete?id=@item.ID" data-toggle="modal" data-target="#confirm-delete"><i class="glyphicon glyphicon-trash"></i></a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <label>CẢNH BÁO</label>
            </div>
            <div class="modal-body">
                <p>Xóa dữ liệu này có thể xóa đi các dữ liệu có liên quan</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a class="btn btn-danger btn-ok">Delete</a>
            </div>
        </div>
    </div>
</div>