Shopper/Shopper/Areas/Admin/Controllers/ChangePasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shopper.Models.DAO;
using Shopper.Common;
using Shopper.Areas.Admin.Models;

namespace Shopper.Areas.Admin.Controllers
{
    public class ChangePasswordController : BaseController
    {
        UserDAO daoUser = new UserDAO();
        //
        // GET: /Admin/ChangePassword/
        public ActionResult Index()
        {
            ChangepasswordModel model = new ChangepasswordModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ChangepasswordModel model)
        {
            if (ModelState.IsValid)
            {
                var session = Session[Common.Constans.USER_SESSION] as LoginSession;
                var user = daoUser.getByName(session.UserName);
                model.newPassword = Common.Encrytor.Encrypt(model.newPassword);
                if (daoUser.changePassword(user.ID, model.newPassword))
                {
                    SetAlert("Đổi mật khẩu thành công", "success");
                    Session[Common.Constans.USER_SESSION] = null;
                    return RedirectToAction("Login", "Regestor");
                }
                else
                {
                    SetAlert("Đổi mật khẩu thất bại, hãy thử lại", "error");
                    return View(model);
                }
            }
            return View(model);
        }
    }
}

Shopper/Shopper/Areas/Admin/Views/ChangePassword/Index.cshtml
@model Shopper.Areas.Admin.Models.ChangepasswordModel
@{
    ViewBag.Title = "Đổi mật khẩu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    Đổi Mật Khẩu
}

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-body">
                @using (Html.BeginForm("Index", "ChangePassword", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true)

                    <div class="form-group">
                        @Html.LabelFor(model => model.newPassword)
                        @Html.PasswordFor(model => model.newPassword, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.newPassword, "", new { @style = "color:red;" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.confirmPassword)
                        @Html.PasswordFor(model => model.confirmPassword, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.confirmPassword, "", new { @style = "color:red;" })
                    </div>

                    <input type="submit" value="Đổi Mật Khẩu" class="btn btn-primary btn-lg btn-block" />
                }
            </div>
        </div>
    </div>

</div>